services:
  redis:
    image: docker.io/redis:7.2.3-alpine
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - /data/redis:/var/lib/redis/
    ports:
      - 127.0.0.1:16379:6379
    command: redis-server /etc/redis/redis.conf
    restart: always