apiVersion: v1
kind: Pod
metadata:
  name: redis

spec:
  containers:
    - name: app
      image: docker.io/redis:7.2.3-alpine
      volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/redis.conf
        - name: redis-data
          mountPath: /var/lib/redis/
      ports:
        - hostIP: 127.0.0.1
          hostPort: 16379
          containerPort: 6379
      command: ['redis-server', '/etc/redis/redis.conf']
  
  volumes:
    - name: redis-config
      hostPath:
        path: ./redis.conf
    - name: redis-data
      hostPath:
        path: ./data